# Generated by Django 3.2.8 on 2022-05-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooom',
            new_name='Room',
        ),
    ]
